name: Build and Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}
          sudo chmod -R 755 ${{ github.workspace }}
        continue-on-error: true
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          clean: true
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Remove node_modules
        run: rm -rf node_modules
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm run compile
      - run: pnpm run test
